#pragma once

#ifndef CLAW_CLIENT_NAME
#define CLAW_CLIENT_NAME "claw_1"
#endif

#ifndef CLAW_CLIENT_WIFI_SSID
#define CLAW_CLIENT_WIFI_SSID "fegrue-hotspot"
#endif

#ifndef CLAW_CLIENT_WIFI_PASSWORD
#define CLAW_CLIENT_WIFI_PASSWORD "3C031AE230FD5B6D4D0FE06567"
#endif

#ifndef CLAW_SERVER_TCP_PORT
#define CLAW_SERVER_TCP_PORT 3333
#endif

#ifndef CLAW_CLIENT_RECONNECT_INTERVAL_MS
#define CLAW_CLIENT_RECONNECT_INTERVAL_MS 2000
#endif

#ifndef CLAW_SERVER_AP_SSID
#define CLAW_SERVER_AP_SSID "clawmachine_debug"
#endif

#ifndef CLAW_SERVER_AP_PASSWORD
#define CLAW_SERVER_AP_PASSWORD ""
#endif

#ifndef CLAW_SERVER_MAX_TCP_CLIENTS
#define CLAW_SERVER_MAX_TCP_CLIENTS 6
#endif

#ifndef CLAW_SERVER_HEARTBEAT_INTERVAL_MS
#define CLAW_SERVER_HEARTBEAT_INTERVAL_MS 5000
#endif

#ifndef CLAW_SERVER_OTA_HOSTNAME
#define CLAW_SERVER_OTA_HOSTNAME "claw_server"
#endif
