#pragma once

#ifndef CLAW_CLIENT_NAME
#define CLAW_CLIENT_NAME "claw_1"
#endif

#ifndef CLAW_CLIENT_WIFI_SSID
#define CLAW_CLIENT_WIFI_SSID "fegrue-hotspot"
#endif

#ifndef CLAW_CLIENT_WIFI_PASSWORD
#define CLAW_CLIENT_WIFI_PASSWORD "3C031AE230FD5B6D4D0FE06567"
#endif

#ifndef CLAW_SERVER_TCP_PORT
#define CLAW_SERVER_TCP_PORT 3333
#endif

#ifndef CLAW_CONNECTION_RETRY_INTERVAL_MS
#define CLAW_CONNECTION_RETRY_INTERVAL_MS 2000
#endif

#ifndef CLAW_MQTT_BROKER_HOST
#define CLAW_MQTT_BROKER_HOST "192.168.178.38"
#endif

#ifndef CLAW_MQTT_BROKER_PORT
#define CLAW_MQTT_BROKER_PORT 1883
#endif

#ifndef CLAW_CONTROL_PANEL_CLIENT_ID
#define CLAW_CONTROL_PANEL_CLIENT_ID "control_panel"
#endif

#ifndef CLAW_MOTOR_CONTROLLER_CLIENT_ID
#define CLAW_MOTOR_CONTROLLER_CLIENT_ID "motor_controller"
#endif
